export * from "./Nav";
export * from "./Home";
export * from "./About";
export * from "./Services";
export * from "./Rates";
export * from "./Testimonials";
export * from "./Blog";
export * from "./Contact";
export * from "./Footer";
